class TicketCardModel {
  final String ticketId;
  final String operator;
  final String transportType;
  final String logoUrl;
  final String from;
  final String to;
  final String departureDate; // Format: YYYY-MM-DD
  final String departureTime; // Format: HH:mm
  final String arrivalTime; // Optional
  final String duration; // Optional
  final String ticketClass; // e.g., AC Business, Non-AC
  final double fare;
  final String currency;
  final int seatsAvailable;
  final String status; // Open, Full, Cancelled

  TicketCardModel({
    required this.ticketId,
    required this.operator,
    required this.transportType,
    required this.logoUrl,
    required this.from,
    required this.to,
    required this.departureDate,
    required this.departureTime,
    required this.arrivalTime,
    required this.duration,
    required this.ticketClass,
    required this.fare,
    this.currency = 'BDT',
    required this.seatsAvailable,
    required this.status,
  });
}

final List<TicketCardModel> ticketList = [
  TicketCardModel(
    ticketId: 'BDX-001',
    operator: 'Shohagh Paribahan',
    transportType: 'Bus',
    logoUrl: 'assets/logos/shohagh.png',
    from: 'Dhaka (Gabtoli)',
    to: 'Cox\'s Bazar',
    departureDate: '2025-07-25',
    departureTime: '07:45',
    arrivalTime: '15:30',
    duration: '7h 45m',
    ticketClass: 'AC Business',
    fare: 850,
    seatsAvailable: 12,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-002',
    operator: 'Green Line Paribahan',
    transportType: 'Bus',
    logoUrl: 'assets/logos/greenline.png',
    from: 'Dhaka (Kalyanpur)',
    to: 'Chattogram',
    departureDate: '2025-07-25',
    departureTime: '08:00',
    arrivalTime: '14:15',
    duration: '6h 15m',
    ticketClass: 'AC Sleeper',
    fare: 1100,
    seatsAvailable: 8,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-003',
    operator: 'Hanif Enterprise',
    transportType: 'Bus',
    logoUrl: 'assets/logos/hanif.png',
    from: 'Dhaka (Arambagh)',
    to: 'Sylhet',
    departureDate: '2025-07-25',
    departureTime: '09:15',
    arrivalTime: '15:30',
    duration: '6h 15m',
    ticketClass: 'Non-AC',
    fare: 550,
    seatsAvailable: 15,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-004',
    operator: 'Biman Bangladesh Airlines',
    transportType: 'Flight',
    logoUrl: 'assets/logos/biman.png',
    from: 'Dhaka (DAC)',
    to: 'Cox\'s Bazar (CXB)',
    departureDate: '2025-07-25',
    departureTime: '10:30',
    arrivalTime: '11:20',
    duration: '50m',
    ticketClass: 'Economy',
    fare: 4500,
    seatsAvailable: 4,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-005',
    operator: 'Shonar Bangla Express',
    transportType: 'Train',
    logoUrl: 'assets/logos/train.png',
    from: 'Dhaka (Kamalapur)',
    to: 'Chattogram',
    departureDate: '2025-07-25',
    departureTime: '06:20',
    arrivalTime: '11:45',
    duration: '5h 25m',
    ticketClass: 'AC Chair',
    fare: 760,
    seatsAvailable: 10,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-006',
    operator: 'Soudia Paribahan',
    transportType: 'Bus',
    logoUrl: 'assets/logos/soudia.png',
    from: 'Dhaka (Gabtoli)',
    to: 'Rangpur',
    departureDate: '2025-07-25',
    departureTime: '21:00',
    arrivalTime: '05:30',
    duration: '8h 30m',
    ticketClass: 'AC Business',
    fare: 950,
    seatsAvailable: 6,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-007',
    operator: 'Biman Bangladesh Airlines',
    transportType: 'Flight',
    logoUrl: 'assets/logos/biman.png',
    from: 'Dhaka (DAC)',
    to: 'Sylhet (ZYL)',
    departureDate: '2025-07-25',
    departureTime: '12:00',
    arrivalTime: '12:50',
    duration: '50m',
    ticketClass: 'Business',
    fare: 6000,
    seatsAvailable: 3,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-008',
    operator: 'BIWTC Launch Service',
    transportType: 'Launch',
    logoUrl: 'assets/logos/launch.png',
    from: 'Dhaka (Sadarghat)',
    to: 'Barisal',
    departureDate: '2025-07-25',
    departureTime: '20:30',
    arrivalTime: '05:30',
    duration: '9h 00m',
    ticketClass: 'Cabin',
    fare: 900,
    seatsAvailable: 5,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-009',
    operator: 'Green Line Waterbus',
    transportType: 'Launch',
    logoUrl: 'assets/logos/greenline.png',
    from: 'Dhaka (Sadarghat)',
    to: 'Chandpur',
    departureDate: '2025-07-25',
    departureTime: '14:00',
    arrivalTime: '16:30',
    duration: '2h 30m',
    ticketClass: 'Business',
    fare: 600,
    seatsAvailable: 9,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-010',
    operator: 'Shyamoli Paribahan',
    transportType: 'Bus',
    logoUrl: 'assets/logos/shyamoli.png',
    from: 'Dhaka (Kalyanpur)',
    to: 'Jessore',
    departureDate: '2025-07-25',
    departureTime: '22:00',
    arrivalTime: '06:30',
    duration: '8h 30m',
    ticketClass: 'Non-AC',
    fare: 500,
    seatsAvailable: 11,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-011',
    operator: 'Ena Transport',
    transportType: 'Bus',
    logoUrl: 'assets/logos/ena.png',
    from: 'Dhaka (Uttara)',
    to: 'Sylhet',
    departureDate: '2025-07-25',
    departureTime: '08:30',
    arrivalTime: '15:00',
    duration: '6h 30m',
    ticketClass: 'AC Business',
    fare: 800,
    seatsAvailable: 13,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-012',
    operator: 'Shohagh Paribahan',
    transportType: 'Bus',
    logoUrl: 'assets/logos/shohagh.png',
    from: 'Chattogram',
    to: 'Dhaka (Gabtoli)',
    departureDate: '2025-07-25',
    departureTime: '18:00',
    arrivalTime: '00:00',
    duration: '6h 00m',
    ticketClass: 'AC Sleeper',
    fare: 1000,
    seatsAvailable: 7,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-013',
    operator: 'Padma Express',
    transportType: 'Train',
    logoUrl: 'assets/logos/train.png',
    from: 'Dhaka (Kamalapur)',
    to: 'Rajshahi',
    departureDate: '2025-07-25',
    departureTime: '23:00',
    arrivalTime: '06:00',
    duration: '7h 00m',
    ticketClass: 'AC Berth',
    fare: 950,
    seatsAvailable: 5,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-014',
    operator: 'US-Bangla Airlines',
    transportType: 'Flight',
    logoUrl: 'assets/logos/usbangla.png',
    from: 'Dhaka (DAC)',
    to: 'Chattogram (CGP)',
    departureDate: '2025-07-25',
    departureTime: '09:20',
    arrivalTime: '10:05',
    duration: '45m',
    ticketClass: 'Economy',
    fare: 3500,
    seatsAvailable: 6,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-015',
    operator: 'Green Line Paribahan',
    transportType: 'Bus',
    logoUrl: 'assets/logos/greenline.png',
    from: 'Dhaka (Gabtoli)',
    to: 'Khulna',
    departureDate: '2025-07-25',
    departureTime: '22:30',
    arrivalTime: '07:30',
    duration: '9h 00m',
    ticketClass: 'AC Business',
    fare: 1050,
    seatsAvailable: 8,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-016',
    operator: 'Mitali Express',
    transportType: 'Train',
    logoUrl: 'assets/logos/train.png',
    from: 'Dhaka (Kamalapur)',
    to: 'New Jalpaiguri',
    departureDate: '2025-07-25',
    departureTime: '21:45',
    arrivalTime: '08:00',
    duration: '10h 15m',
    ticketClass: 'AC Berth',
    fare: 1250,
    seatsAvailable: 3,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-017',
    operator: 'Shonar Bangla Express',
    transportType: 'Train',
    logoUrl: 'assets/logos/train.png',
    from: 'Chattogram',
    to: 'Dhaka (Kamalapur)',
    departureDate: '2025-07-25',
    departureTime: '19:00',
    arrivalTime: '00:30',
    duration: '5h 30m',
    ticketClass: 'AC Chair',
    fare: 760,
    seatsAvailable: 14,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-018',
    operator: 'Biman Bangladesh Airlines',
    transportType: 'Flight',
    logoUrl: 'assets/logos/biman.png',
    from: 'Sylhet (ZYL)',
    to: 'Dhaka (DAC)',
    departureDate: '2025-07-25',
    departureTime: '17:30',
    arrivalTime: '18:20',
    duration: '50m',
    ticketClass: 'Economy',
    fare: 4200,
    seatsAvailable: 5,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-019',
    operator: 'BIWTC Launch Service',
    transportType: 'Launch',
    logoUrl: 'assets/logos/launch.png',
    from: 'Dhaka (Sadarghat)',
    to: 'Patuakhali',
    departureDate: '2025-07-25',
    departureTime: '19:00',
    arrivalTime: '06:00',
    duration: '11h 00m',
    ticketClass: 'Cabin',
    fare: 950,
    seatsAvailable: 6,
    status: 'Open',
  ),
  TicketCardModel(
    ticketId: 'BDX-020',
    operator: 'Ena Transport',
    transportType: 'Bus',
    logoUrl: 'assets/logos/ena.png',
    from: 'Dhaka (Uttara)',
    to: 'Mymensingh',
    departureDate: '2025-07-25',
    departureTime: '16:00',
    arrivalTime: '19:00',
    duration: '3h 00m',
    ticketClass: 'Non-AC',
    fare: 350,
    seatsAvailable: 18,
    status: 'Open',
  ),
];
